stages:
  - stage: UITestsPipelineRun
    variables:
    - group: testPipelinesAuthToken
    - name: personalToken
      value: $[variables.personalAuthToken]
    - name: sauceLabsJsonString
      value: $[ stageDependencies.EnvironmentDeploymentBuild.environment_deployment_build.outputs['deploySauceLabs.mSauceLabsAppsID'] ]
    - name: deviceAndroid
      value: "10" #$[variables.deviceAndroid]
    - name: deviceIos
      value: "11" #$[variables.deviceIos]
    - name: iosPipelineID
      value: "429" #$[variables.iosPipelineID]
    - name: androidPipelineID
      value: "418" #$[variables.androidPipelineID]
    - name: azureProjectID
      value: "fc594814-b424-4140-ad9f-82e3cb736325" #$[variables.azureProjectID]
    - name: dataCenter
      value: "eu" #$[variables.dataCenter]
    jobs:
      - job: run_tests_pipeline
        displayName: 'Start UITests Pipeline'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: 'npm-steps.yml'
            parameters:
              workingDirectory: 'CI/templates'
          - script: 'npm run startPipeline --jsonStringBase64="$(sauceLabsJsonString)" --token="$(personalToken)" --deviceAndroid=$(deviceAndroid) --deviceIos=$(deviceIos) --androidPipelineID=$(androidPipelineID) --iosPipelineID=$(iosPipelineID) --azureProjectID=$(azureProjectID) --dataCenter=$(dataCenter)'
            timeoutInMinutes: 120
            workingDirectory: 'CI/templates'
            failOnStderr: true
